# Generated by Django 5.2.7 on 2025-10-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("email__isnull", False), models.Q(("email", ""), _negated=True)
                ),
                fields=("email",),
                name="uniq_user_email_non_null",
            ),
        ),
    ]
