name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: library
          POSTGRES_USER: library
          POSTGRES_PASSWORD: library
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U library -d library"
          --health-interval=5s --health-timeout=3s --health-retries=10

    env:
      SECRET_KEY: ci-secret
      DEBUG: "0"
      POSTGRES_DB: library
      POSTGRES_USER: library
      POSTGRES_PASSWORD: library
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: "5432"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install Poetry
        run: pip install poetry
      - name: Install deps
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
      - name: Migrate
        run: python manage.py migrate
      - name: Lint
        run: |
          black --check .
          isort --check-only .
          flake8 .
      - name: Tests
        run: pytest -q
